### PR TITLE
Add UT for stemcells, package options, tasks and task output.

### PR DESCRIPTION
**Pull request by zhanggbj**
Hi,
This patch add unit test for /stemcells and /sl/package/{package id}/options. They all passed. Thanks.

### CODE REVIEW

**Comment by zhanggbj** [comment]
Hi,
It seems Travis check keeps failing on this step today. 

$ go version
go version go1.5.3 linux/amd64
go.env
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/travis/gopath"
GORACE=""
GOROOT="/home/travis/.gimme/versions/go1.5.3.linux.amd64"
GOTOOLDIR="/home/travis/.gimme/versions/go1.5.3.linux.amd64/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
before_install.1
3.28s$ go get github.com/tools/godep
before_install.2
4.12s$ go get github.com/onsi/ginkgo/ginkgo
1.86s$ go get golang.org/x/tools/cmd/vet
package golang.org/x/tools/cmd/vet: cannot find package "golang.org/x/tools/cmd/vet" in any of:
    /home/travis/.gimme/versions/go1.5.3.linux.amd64/src/golang.org/x/tools/cmd/vet (from $GOROOT)
    /home/travis/gopath/src/golang.org/x/tools/cmd/vet (from $GOPATH)
The command "go get golang.org/x/tools/cmd/vet" failed and exited with 1 during .

**Comment by zhanggbj** [comment]
Trigger a new travis build.

**Comment by zhanggbj** [comment]
Hi dr.max, @maximilien 
Sorry for submit such a long commit. They are supposed to be in separated PR. I'll try it next time.
And currently I commented out go vet tool in .travis.yml to make PR ready for review, because the original one doesn't work and didn't find a proper new one yet. (I'll fix this later)

Thank you for your code review in advance.

**Comment by zhanggbj** [comment]
Travis issue fixed.  Thanks

**Comment by maximilien** [comment]
Should you just close this one?

**Pull request closed without merging**
