### PR TITLE
Add a script 

### PR DESCRIPTION
**Pull request by gnanbj**
Add a script for director migration validation

### CODE REVIEW

**Comment by maximilien** [comment]
@gnanbj thanks for the contribution. However, seems that Travis is not happy.

I know @mattcui had a similar issue with another PR. Maybe you can talk to him to see what he did. Please update PR and reopen. Thanks.

**Comment by mattcui** [comment]
@maximilien it should be because softlayer-go is out of date in Godeps, could you please help update Godeps?

@gnanbj

**Comment by maximilien** [comment]
OK @mattcui and @gnanbj, done in 2b0da17e72301504d825bc6a1fc65e41355f7463

Waiting to see if Travis passes.

**Comment by maximilien** [comment]
@mattcui and @gnanbj still failing Travis...

**Comment by maximilien** [comment]
@gnanbj this is still failing. Even after pulling in the change from @mattcui which fixed his PR

**Comment by gnanbj** [comment]
Hi max,
 
Sorry, I am not familiar with Travis, maybe matt can help...
 
Best Regards,
Cathy -- Nan Gao (高楠)==============================================Bluemix Fabric TestTel: 86-10-82451196Email: gnanbj@cn.ibm.comAddress: 2/F, Ring Building, ZhongGuanCun Software Park , Dongbeiwang West Road No.8, ShangDi, Haidian District, Beijing 100193==============================================
 
 
----- Original message -----From: "dr.max" notifications@github.comTo: maximilien/bosh-softlayer-stemcells bosh-softlayer-stemcells@noreply.github.comCc: Nan MJ Gao/China/IBM@IBMCNSubject: Re: [bosh-softlayer-stemcells] Add a script (#16)Date: Wed, Mar 9, 2016 9:51 AM 
@gnanbj this is still failing. Even after pulling in the change from @mattcui which fixed his.

**Pull request merged**
