### PR TITLE
Add ProvisioningBaremetal and TaskJsonOutput methods to bmsclient

### PR DESCRIPTION
**Pull request by jianqiu**
As sl-cpi wants to leverage the bmsclient to communicate with baremetal server, bmsclient needs to provider two additional methods.

### CODE REVIEW

**Comment by maximilien** [comment]
@zhanggbj there are conflicts. Could be you need to rebase do to my previous merges. When you do I will review.

**Comment by maximilien** [comment]
@jianqiu and @zhanggbj this looks great. Just add an integration test and I will merge.

Thanks.

**Comment by jianqiu** [comment]
@maximilien 
Integration testcase had been included. Thanks!

**Comment by maximilien** [comment]
OK looks good. Merging :+1:

**Pull request merged**
